// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DATAPRODUCER_FBS_DATAPRODUCER_H_
#define FLATBUFFERS_GENERATED_DATAPRODUCER_FBS_DATAPRODUCER_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

#include "sctpParameters.h"

namespace FBS {
namespace DataProducer {

struct DumpResponse;
struct DumpResponseBuilder;

struct GetStatsResponse;
struct GetStatsResponseBuilder;

struct SendNotification;
struct SendNotificationBuilder;

inline const ::flatbuffers::TypeTable *DumpResponseTypeTable();

inline const ::flatbuffers::TypeTable *GetStatsResponseTypeTable();

inline const ::flatbuffers::TypeTable *SendNotificationTypeTable();

enum class Type : uint8_t {
  SCTP = 0,
  DIRECT = 1,
  MIN = SCTP,
  MAX = DIRECT
};

inline const Type (&EnumValuesType())[2] {
  static const Type values[] = {
    Type::SCTP,
    Type::DIRECT
  };
  return values;
}

inline const char * const *EnumNamesType() {
  static const char * const names[3] = {
    "SCTP",
    "DIRECT",
    nullptr
  };
  return names;
}

inline const char *EnumNameType(Type e) {
  if (::flatbuffers::IsOutRange(e, Type::SCTP, Type::DIRECT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesType()[index];
}

struct DumpResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DumpResponseBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return DumpResponseTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TYPE = 6,
    VT_SCTPSTREAMPARAMETERS = 8,
    VT_LABEL = 10,
    VT_PROTOCOL = 12,
    VT_PAUSED = 14
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  FBS::DataProducer::Type type() const {
    return static_cast<FBS::DataProducer::Type>(GetField<uint8_t>(VT_TYPE, 0));
  }
  const FBS::SctpParameters::SctpStreamParameters *sctpStreamParameters() const {
    return GetPointer<const FBS::SctpParameters::SctpStreamParameters *>(VT_SCTPSTREAMPARAMETERS);
  }
  const ::flatbuffers::String *label() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LABEL);
  }
  const ::flatbuffers::String *protocol() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROTOCOL);
  }
  bool paused() const {
    return GetField<uint8_t>(VT_PAUSED, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           VerifyOffset(verifier, VT_SCTPSTREAMPARAMETERS) &&
           verifier.VerifyTable(sctpStreamParameters()) &&
           VerifyOffsetRequired(verifier, VT_LABEL) &&
           verifier.VerifyString(label()) &&
           VerifyOffsetRequired(verifier, VT_PROTOCOL) &&
           verifier.VerifyString(protocol()) &&
           VerifyField<uint8_t>(verifier, VT_PAUSED, 1) &&
           verifier.EndTable();
  }
};

struct DumpResponseBuilder {
  typedef DumpResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(DumpResponse::VT_ID, id);
  }
  void add_type(FBS::DataProducer::Type type) {
    fbb_.AddElement<uint8_t>(DumpResponse::VT_TYPE, static_cast<uint8_t>(type), 0);
  }
  void add_sctpStreamParameters(::flatbuffers::Offset<FBS::SctpParameters::SctpStreamParameters> sctpStreamParameters) {
    fbb_.AddOffset(DumpResponse::VT_SCTPSTREAMPARAMETERS, sctpStreamParameters);
  }
  void add_label(::flatbuffers::Offset<::flatbuffers::String> label) {
    fbb_.AddOffset(DumpResponse::VT_LABEL, label);
  }
  void add_protocol(::flatbuffers::Offset<::flatbuffers::String> protocol) {
    fbb_.AddOffset(DumpResponse::VT_PROTOCOL, protocol);
  }
  void add_paused(bool paused) {
    fbb_.AddElement<uint8_t>(DumpResponse::VT_PAUSED, static_cast<uint8_t>(paused), 0);
  }
  explicit DumpResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DumpResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DumpResponse>(end);
    fbb_.Required(o, DumpResponse::VT_ID);
    fbb_.Required(o, DumpResponse::VT_LABEL);
    fbb_.Required(o, DumpResponse::VT_PROTOCOL);
    return o;
  }
};

inline ::flatbuffers::Offset<DumpResponse> CreateDumpResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    FBS::DataProducer::Type type = FBS::DataProducer::Type::SCTP,
    ::flatbuffers::Offset<FBS::SctpParameters::SctpStreamParameters> sctpStreamParameters = 0,
    ::flatbuffers::Offset<::flatbuffers::String> label = 0,
    ::flatbuffers::Offset<::flatbuffers::String> protocol = 0,
    bool paused = false) {
  DumpResponseBuilder builder_(_fbb);
  builder_.add_protocol(protocol);
  builder_.add_label(label);
  builder_.add_sctpStreamParameters(sctpStreamParameters);
  builder_.add_id(id);
  builder_.add_paused(paused);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DumpResponse> CreateDumpResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    FBS::DataProducer::Type type = FBS::DataProducer::Type::SCTP,
    ::flatbuffers::Offset<FBS::SctpParameters::SctpStreamParameters> sctpStreamParameters = 0,
    const char *label = nullptr,
    const char *protocol = nullptr,
    bool paused = false) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto label__ = label ? _fbb.CreateString(label) : 0;
  auto protocol__ = protocol ? _fbb.CreateString(protocol) : 0;
  return FBS::DataProducer::CreateDumpResponse(
      _fbb,
      id__,
      type,
      sctpStreamParameters,
      label__,
      protocol__,
      paused);
}

struct GetStatsResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GetStatsResponseBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return GetStatsResponseTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_LABEL = 6,
    VT_PROTOCOL = 8,
    VT_MESSAGESRECEIVED = 10,
    VT_BYTESRECEIVED = 12,
    VT_BUFFEREDAMOUNT = 14
  };
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  const ::flatbuffers::String *label() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LABEL);
  }
  const ::flatbuffers::String *protocol() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROTOCOL);
  }
  uint64_t messagesReceived() const {
    return GetField<uint64_t>(VT_MESSAGESRECEIVED, 0);
  }
  uint64_t bytesReceived() const {
    return GetField<uint64_t>(VT_BYTESRECEIVED, 0);
  }
  uint32_t bufferedAmount() const {
    return GetField<uint32_t>(VT_BUFFEREDAMOUNT, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           VerifyOffsetRequired(verifier, VT_LABEL) &&
           verifier.VerifyString(label()) &&
           VerifyOffsetRequired(verifier, VT_PROTOCOL) &&
           verifier.VerifyString(protocol()) &&
           VerifyField<uint64_t>(verifier, VT_MESSAGESRECEIVED, 8) &&
           VerifyField<uint64_t>(verifier, VT_BYTESRECEIVED, 8) &&
           VerifyField<uint32_t>(verifier, VT_BUFFEREDAMOUNT, 4) &&
           verifier.EndTable();
  }
};

struct GetStatsResponseBuilder {
  typedef GetStatsResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(GetStatsResponse::VT_TIMESTAMP, timestamp, 0);
  }
  void add_label(::flatbuffers::Offset<::flatbuffers::String> label) {
    fbb_.AddOffset(GetStatsResponse::VT_LABEL, label);
  }
  void add_protocol(::flatbuffers::Offset<::flatbuffers::String> protocol) {
    fbb_.AddOffset(GetStatsResponse::VT_PROTOCOL, protocol);
  }
  void add_messagesReceived(uint64_t messagesReceived) {
    fbb_.AddElement<uint64_t>(GetStatsResponse::VT_MESSAGESRECEIVED, messagesReceived, 0);
  }
  void add_bytesReceived(uint64_t bytesReceived) {
    fbb_.AddElement<uint64_t>(GetStatsResponse::VT_BYTESRECEIVED, bytesReceived, 0);
  }
  void add_bufferedAmount(uint32_t bufferedAmount) {
    fbb_.AddElement<uint32_t>(GetStatsResponse::VT_BUFFEREDAMOUNT, bufferedAmount, 0);
  }
  explicit GetStatsResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GetStatsResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GetStatsResponse>(end);
    fbb_.Required(o, GetStatsResponse::VT_LABEL);
    fbb_.Required(o, GetStatsResponse::VT_PROTOCOL);
    return o;
  }
};

inline ::flatbuffers::Offset<GetStatsResponse> CreateGetStatsResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t timestamp = 0,
    ::flatbuffers::Offset<::flatbuffers::String> label = 0,
    ::flatbuffers::Offset<::flatbuffers::String> protocol = 0,
    uint64_t messagesReceived = 0,
    uint64_t bytesReceived = 0,
    uint32_t bufferedAmount = 0) {
  GetStatsResponseBuilder builder_(_fbb);
  builder_.add_bytesReceived(bytesReceived);
  builder_.add_messagesReceived(messagesReceived);
  builder_.add_timestamp(timestamp);
  builder_.add_bufferedAmount(bufferedAmount);
  builder_.add_protocol(protocol);
  builder_.add_label(label);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<GetStatsResponse> CreateGetStatsResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t timestamp = 0,
    const char *label = nullptr,
    const char *protocol = nullptr,
    uint64_t messagesReceived = 0,
    uint64_t bytesReceived = 0,
    uint32_t bufferedAmount = 0) {
  auto label__ = label ? _fbb.CreateString(label) : 0;
  auto protocol__ = protocol ? _fbb.CreateString(protocol) : 0;
  return FBS::DataProducer::CreateGetStatsResponse(
      _fbb,
      timestamp,
      label__,
      protocol__,
      messagesReceived,
      bytesReceived,
      bufferedAmount);
}

struct SendNotification FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SendNotificationBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return SendNotificationTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PPID = 4,
    VT_DATA = 6,
    VT_SUBCHANNELS = 8,
    VT_REQUIREDSUBCHANNEL = 10
  };
  uint32_t ppid() const {
    return GetField<uint32_t>(VT_PPID, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  const ::flatbuffers::Vector<uint16_t> *subchannels() const {
    return GetPointer<const ::flatbuffers::Vector<uint16_t> *>(VT_SUBCHANNELS);
  }
  ::flatbuffers::Optional<uint16_t> requiredSubchannel() const {
    return GetOptional<uint16_t, uint16_t>(VT_REQUIREDSUBCHANNEL);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PPID, 4) &&
           VerifyOffsetRequired(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           VerifyOffset(verifier, VT_SUBCHANNELS) &&
           verifier.VerifyVector(subchannels()) &&
           VerifyField<uint16_t>(verifier, VT_REQUIREDSUBCHANNEL, 2) &&
           verifier.EndTable();
  }
};

struct SendNotificationBuilder {
  typedef SendNotification Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ppid(uint32_t ppid) {
    fbb_.AddElement<uint32_t>(SendNotification::VT_PPID, ppid, 0);
  }
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(SendNotification::VT_DATA, data);
  }
  void add_subchannels(::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> subchannels) {
    fbb_.AddOffset(SendNotification::VT_SUBCHANNELS, subchannels);
  }
  void add_requiredSubchannel(uint16_t requiredSubchannel) {
    fbb_.AddElement<uint16_t>(SendNotification::VT_REQUIREDSUBCHANNEL, requiredSubchannel);
  }
  explicit SendNotificationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SendNotification> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SendNotification>(end);
    fbb_.Required(o, SendNotification::VT_DATA);
    return o;
  }
};

inline ::flatbuffers::Offset<SendNotification> CreateSendNotification(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t ppid = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> subchannels = 0,
    ::flatbuffers::Optional<uint16_t> requiredSubchannel = ::flatbuffers::nullopt) {
  SendNotificationBuilder builder_(_fbb);
  builder_.add_subchannels(subchannels);
  builder_.add_data(data);
  builder_.add_ppid(ppid);
  if(requiredSubchannel) { builder_.add_requiredSubchannel(*requiredSubchannel); }
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SendNotification> CreateSendNotificationDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t ppid = 0,
    const std::vector<uint8_t> *data = nullptr,
    const std::vector<uint16_t> *subchannels = nullptr,
    ::flatbuffers::Optional<uint16_t> requiredSubchannel = ::flatbuffers::nullopt) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  auto subchannels__ = subchannels ? _fbb.CreateVector<uint16_t>(*subchannels) : 0;
  return FBS::DataProducer::CreateSendNotification(
      _fbb,
      ppid,
      data__,
      subchannels__,
      requiredSubchannel);
}

inline const ::flatbuffers::TypeTable *TypeTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::DataProducer::TypeTypeTable
  };
  static const char * const names[] = {
    "SCTP",
    "DIRECT"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_ENUM, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *DumpResponseTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_SEQUENCE, 0, 1 },
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_BOOL, 0, -1 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::DataProducer::TypeTypeTable,
    FBS::SctpParameters::SctpStreamParametersTypeTable
  };
  static const char * const names[] = {
    "id",
    "type",
    "sctpStreamParameters",
    "label",
    "protocol",
    "paused"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 6, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *GetStatsResponseTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_ULONG, 0, -1 },
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_ULONG, 0, -1 },
    { ::flatbuffers::ET_ULONG, 0, -1 },
    { ::flatbuffers::ET_UINT, 0, -1 }
  };
  static const char * const names[] = {
    "timestamp",
    "label",
    "protocol",
    "messagesReceived",
    "bytesReceived",
    "bufferedAmount"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 6, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *SendNotificationTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UINT, 0, -1 },
    { ::flatbuffers::ET_UCHAR, 1, -1 },
    { ::flatbuffers::ET_USHORT, 1, -1 },
    { ::flatbuffers::ET_USHORT, 0, -1 }
  };
  static const char * const names[] = {
    "ppid",
    "data",
    "subchannels",
    "requiredSubchannel"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 4, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

}  // namespace DataProducer
}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_DATAPRODUCER_FBS_DATAPRODUCER_H_
