// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_LIBURING_FBS_LIBURING_H_
#define FLATBUFFERS_GENERATED_LIBURING_FBS_LIBURING_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace FBS {
namespace LibUring {

struct Dump;
struct DumpBuilder;

inline const ::flatbuffers::TypeTable *DumpTypeTable();

struct Dump FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DumpBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return DumpTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SQEPROCESSCOUNT = 4,
    VT_SQEMISSCOUNT = 6,
    VT_USERDATAMISSCOUNT = 8
  };
  uint64_t sqeProcessCount() const {
    return GetField<uint64_t>(VT_SQEPROCESSCOUNT, 0);
  }
  uint64_t sqeMissCount() const {
    return GetField<uint64_t>(VT_SQEMISSCOUNT, 0);
  }
  uint64_t userDataMissCount() const {
    return GetField<uint64_t>(VT_USERDATAMISSCOUNT, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_SQEPROCESSCOUNT, 8) &&
           VerifyField<uint64_t>(verifier, VT_SQEMISSCOUNT, 8) &&
           VerifyField<uint64_t>(verifier, VT_USERDATAMISSCOUNT, 8) &&
           verifier.EndTable();
  }
};

struct DumpBuilder {
  typedef Dump Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_sqeProcessCount(uint64_t sqeProcessCount) {
    fbb_.AddElement<uint64_t>(Dump::VT_SQEPROCESSCOUNT, sqeProcessCount, 0);
  }
  void add_sqeMissCount(uint64_t sqeMissCount) {
    fbb_.AddElement<uint64_t>(Dump::VT_SQEMISSCOUNT, sqeMissCount, 0);
  }
  void add_userDataMissCount(uint64_t userDataMissCount) {
    fbb_.AddElement<uint64_t>(Dump::VT_USERDATAMISSCOUNT, userDataMissCount, 0);
  }
  explicit DumpBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Dump> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Dump>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Dump> CreateDump(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t sqeProcessCount = 0,
    uint64_t sqeMissCount = 0,
    uint64_t userDataMissCount = 0) {
  DumpBuilder builder_(_fbb);
  builder_.add_userDataMissCount(userDataMissCount);
  builder_.add_sqeMissCount(sqeMissCount);
  builder_.add_sqeProcessCount(sqeProcessCount);
  return builder_.Finish();
}

inline const ::flatbuffers::TypeTable *DumpTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_ULONG, 0, -1 },
    { ::flatbuffers::ET_ULONG, 0, -1 },
    { ::flatbuffers::ET_ULONG, 0, -1 }
  };
  static const char * const names[] = {
    "sqeProcessCount",
    "sqeMissCount",
    "userDataMissCount"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 3, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

}  // namespace LibUring
}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_LIBURING_FBS_LIBURING_H_
