// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RTPPACKET_FBS_RTPPACKET_H_
#define FLATBUFFERS_GENERATED_RTPPACKET_FBS_RTPPACKET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

#include "common.h"

namespace FBS {
namespace RtpPacket {

struct Dump;
struct DumpBuilder;

inline const ::flatbuffers::TypeTable *DumpTypeTable();

struct Dump FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DumpBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return DumpTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOADTYPE = 4,
    VT_SEQUENCENUMBER = 6,
    VT_TIMESTAMP = 8,
    VT_MARKER = 10,
    VT_SSRC = 12,
    VT_ISKEYFRAME = 14,
    VT_SIZE = 16,
    VT_PAYLOADSIZE = 18,
    VT_SPATIALLAYER = 20,
    VT_TEMPORALLAYER = 22,
    VT_MID = 24,
    VT_RID = 26,
    VT_RRID = 28,
    VT_WIDESEQUENCENUMBER = 30
  };
  uint8_t payloadType() const {
    return GetField<uint8_t>(VT_PAYLOADTYPE, 0);
  }
  uint16_t sequenceNumber() const {
    return GetField<uint16_t>(VT_SEQUENCENUMBER, 0);
  }
  uint32_t timestamp() const {
    return GetField<uint32_t>(VT_TIMESTAMP, 0);
  }
  bool marker() const {
    return GetField<uint8_t>(VT_MARKER, 0) != 0;
  }
  uint32_t ssrc() const {
    return GetField<uint32_t>(VT_SSRC, 0);
  }
  bool isKeyFrame() const {
    return GetField<uint8_t>(VT_ISKEYFRAME, 0) != 0;
  }
  uint64_t size() const {
    return GetField<uint64_t>(VT_SIZE, 0);
  }
  uint64_t payloadSize() const {
    return GetField<uint64_t>(VT_PAYLOADSIZE, 0);
  }
  uint8_t spatialLayer() const {
    return GetField<uint8_t>(VT_SPATIALLAYER, 0);
  }
  uint8_t temporalLayer() const {
    return GetField<uint8_t>(VT_TEMPORALLAYER, 0);
  }
  const ::flatbuffers::String *mid() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MID);
  }
  const ::flatbuffers::String *rid() const {
    return GetPointer<const ::flatbuffers::String *>(VT_RID);
  }
  const ::flatbuffers::String *rrid() const {
    return GetPointer<const ::flatbuffers::String *>(VT_RRID);
  }
  ::flatbuffers::Optional<uint16_t> wideSequenceNumber() const {
    return GetOptional<uint16_t, uint16_t>(VT_WIDESEQUENCENUMBER);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOADTYPE, 1) &&
           VerifyField<uint16_t>(verifier, VT_SEQUENCENUMBER, 2) &&
           VerifyField<uint32_t>(verifier, VT_TIMESTAMP, 4) &&
           VerifyField<uint8_t>(verifier, VT_MARKER, 1) &&
           VerifyField<uint32_t>(verifier, VT_SSRC, 4) &&
           VerifyField<uint8_t>(verifier, VT_ISKEYFRAME, 1) &&
           VerifyField<uint64_t>(verifier, VT_SIZE, 8) &&
           VerifyField<uint64_t>(verifier, VT_PAYLOADSIZE, 8) &&
           VerifyField<uint8_t>(verifier, VT_SPATIALLAYER, 1) &&
           VerifyField<uint8_t>(verifier, VT_TEMPORALLAYER, 1) &&
           VerifyOffset(verifier, VT_MID) &&
           verifier.VerifyString(mid()) &&
           VerifyOffset(verifier, VT_RID) &&
           verifier.VerifyString(rid()) &&
           VerifyOffset(verifier, VT_RRID) &&
           verifier.VerifyString(rrid()) &&
           VerifyField<uint16_t>(verifier, VT_WIDESEQUENCENUMBER, 2) &&
           verifier.EndTable();
  }
};

struct DumpBuilder {
  typedef Dump Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payloadType(uint8_t payloadType) {
    fbb_.AddElement<uint8_t>(Dump::VT_PAYLOADTYPE, payloadType, 0);
  }
  void add_sequenceNumber(uint16_t sequenceNumber) {
    fbb_.AddElement<uint16_t>(Dump::VT_SEQUENCENUMBER, sequenceNumber, 0);
  }
  void add_timestamp(uint32_t timestamp) {
    fbb_.AddElement<uint32_t>(Dump::VT_TIMESTAMP, timestamp, 0);
  }
  void add_marker(bool marker) {
    fbb_.AddElement<uint8_t>(Dump::VT_MARKER, static_cast<uint8_t>(marker), 0);
  }
  void add_ssrc(uint32_t ssrc) {
    fbb_.AddElement<uint32_t>(Dump::VT_SSRC, ssrc, 0);
  }
  void add_isKeyFrame(bool isKeyFrame) {
    fbb_.AddElement<uint8_t>(Dump::VT_ISKEYFRAME, static_cast<uint8_t>(isKeyFrame), 0);
  }
  void add_size(uint64_t size) {
    fbb_.AddElement<uint64_t>(Dump::VT_SIZE, size, 0);
  }
  void add_payloadSize(uint64_t payloadSize) {
    fbb_.AddElement<uint64_t>(Dump::VT_PAYLOADSIZE, payloadSize, 0);
  }
  void add_spatialLayer(uint8_t spatialLayer) {
    fbb_.AddElement<uint8_t>(Dump::VT_SPATIALLAYER, spatialLayer, 0);
  }
  void add_temporalLayer(uint8_t temporalLayer) {
    fbb_.AddElement<uint8_t>(Dump::VT_TEMPORALLAYER, temporalLayer, 0);
  }
  void add_mid(::flatbuffers::Offset<::flatbuffers::String> mid) {
    fbb_.AddOffset(Dump::VT_MID, mid);
  }
  void add_rid(::flatbuffers::Offset<::flatbuffers::String> rid) {
    fbb_.AddOffset(Dump::VT_RID, rid);
  }
  void add_rrid(::flatbuffers::Offset<::flatbuffers::String> rrid) {
    fbb_.AddOffset(Dump::VT_RRID, rrid);
  }
  void add_wideSequenceNumber(uint16_t wideSequenceNumber) {
    fbb_.AddElement<uint16_t>(Dump::VT_WIDESEQUENCENUMBER, wideSequenceNumber);
  }
  explicit DumpBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Dump> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Dump>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Dump> CreateDump(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t payloadType = 0,
    uint16_t sequenceNumber = 0,
    uint32_t timestamp = 0,
    bool marker = false,
    uint32_t ssrc = 0,
    bool isKeyFrame = false,
    uint64_t size = 0,
    uint64_t payloadSize = 0,
    uint8_t spatialLayer = 0,
    uint8_t temporalLayer = 0,
    ::flatbuffers::Offset<::flatbuffers::String> mid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> rid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> rrid = 0,
    ::flatbuffers::Optional<uint16_t> wideSequenceNumber = ::flatbuffers::nullopt) {
  DumpBuilder builder_(_fbb);
  builder_.add_payloadSize(payloadSize);
  builder_.add_size(size);
  builder_.add_rrid(rrid);
  builder_.add_rid(rid);
  builder_.add_mid(mid);
  builder_.add_ssrc(ssrc);
  builder_.add_timestamp(timestamp);
  if(wideSequenceNumber) { builder_.add_wideSequenceNumber(*wideSequenceNumber); }
  builder_.add_sequenceNumber(sequenceNumber);
  builder_.add_temporalLayer(temporalLayer);
  builder_.add_spatialLayer(spatialLayer);
  builder_.add_isKeyFrame(isKeyFrame);
  builder_.add_marker(marker);
  builder_.add_payloadType(payloadType);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Dump> CreateDumpDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t payloadType = 0,
    uint16_t sequenceNumber = 0,
    uint32_t timestamp = 0,
    bool marker = false,
    uint32_t ssrc = 0,
    bool isKeyFrame = false,
    uint64_t size = 0,
    uint64_t payloadSize = 0,
    uint8_t spatialLayer = 0,
    uint8_t temporalLayer = 0,
    const char *mid = nullptr,
    const char *rid = nullptr,
    const char *rrid = nullptr,
    ::flatbuffers::Optional<uint16_t> wideSequenceNumber = ::flatbuffers::nullopt) {
  auto mid__ = mid ? _fbb.CreateString(mid) : 0;
  auto rid__ = rid ? _fbb.CreateString(rid) : 0;
  auto rrid__ = rrid ? _fbb.CreateString(rrid) : 0;
  return FBS::RtpPacket::CreateDump(
      _fbb,
      payloadType,
      sequenceNumber,
      timestamp,
      marker,
      ssrc,
      isKeyFrame,
      size,
      payloadSize,
      spatialLayer,
      temporalLayer,
      mid__,
      rid__,
      rrid__,
      wideSequenceNumber);
}

inline const ::flatbuffers::TypeTable *DumpTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UCHAR, 0, -1 },
    { ::flatbuffers::ET_USHORT, 0, -1 },
    { ::flatbuffers::ET_UINT, 0, -1 },
    { ::flatbuffers::ET_BOOL, 0, -1 },
    { ::flatbuffers::ET_UINT, 0, -1 },
    { ::flatbuffers::ET_BOOL, 0, -1 },
    { ::flatbuffers::ET_ULONG, 0, -1 },
    { ::flatbuffers::ET_ULONG, 0, -1 },
    { ::flatbuffers::ET_UCHAR, 0, -1 },
    { ::flatbuffers::ET_UCHAR, 0, -1 },
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_USHORT, 0, -1 }
  };
  static const char * const names[] = {
    "payloadType",
    "sequenceNumber",
    "timestamp",
    "marker",
    "ssrc",
    "isKeyFrame",
    "size",
    "payloadSize",
    "spatialLayer",
    "temporalLayer",
    "mid",
    "rid",
    "rrid",
    "wideSequenceNumber"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 14, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

}  // namespace RtpPacket
}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_RTPPACKET_FBS_RTPPACKET_H_
