// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SRTPPARAMETERS_FBS_SRTPPARAMETERS_H_
#define FLATBUFFERS_GENERATED_SRTPPARAMETERS_FBS_SRTPPARAMETERS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace FBS {
namespace SrtpParameters {

struct SrtpParameters;
struct SrtpParametersBuilder;

inline const ::flatbuffers::TypeTable *SrtpParametersTypeTable();

enum class SrtpCryptoSuite : uint8_t {
  AEAD_AES_256_GCM = 0,
  AEAD_AES_128_GCM = 1,
  AES_CM_128_HMAC_SHA1_80 = 2,
  AES_CM_128_HMAC_SHA1_32 = 3,
  MIN = AEAD_AES_256_GCM,
  MAX = AES_CM_128_HMAC_SHA1_32
};

inline const SrtpCryptoSuite (&EnumValuesSrtpCryptoSuite())[4] {
  static const SrtpCryptoSuite values[] = {
    SrtpCryptoSuite::AEAD_AES_256_GCM,
    SrtpCryptoSuite::AEAD_AES_128_GCM,
    SrtpCryptoSuite::AES_CM_128_HMAC_SHA1_80,
    SrtpCryptoSuite::AES_CM_128_HMAC_SHA1_32
  };
  return values;
}

inline const char * const *EnumNamesSrtpCryptoSuite() {
  static const char * const names[5] = {
    "AEAD_AES_256_GCM",
    "AEAD_AES_128_GCM",
    "AES_CM_128_HMAC_SHA1_80",
    "AES_CM_128_HMAC_SHA1_32",
    nullptr
  };
  return names;
}

inline const char *EnumNameSrtpCryptoSuite(SrtpCryptoSuite e) {
  if (::flatbuffers::IsOutRange(e, SrtpCryptoSuite::AEAD_AES_256_GCM, SrtpCryptoSuite::AES_CM_128_HMAC_SHA1_32)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSrtpCryptoSuite()[index];
}

struct SrtpParameters FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SrtpParametersBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return SrtpParametersTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CRYPTOSUITE = 4,
    VT_KEYBASE64 = 6
  };
  FBS::SrtpParameters::SrtpCryptoSuite cryptoSuite() const {
    return static_cast<FBS::SrtpParameters::SrtpCryptoSuite>(GetField<uint8_t>(VT_CRYPTOSUITE, 0));
  }
  const ::flatbuffers::String *keyBase64() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KEYBASE64);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_CRYPTOSUITE, 1) &&
           VerifyOffsetRequired(verifier, VT_KEYBASE64) &&
           verifier.VerifyString(keyBase64()) &&
           verifier.EndTable();
  }
};

struct SrtpParametersBuilder {
  typedef SrtpParameters Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cryptoSuite(FBS::SrtpParameters::SrtpCryptoSuite cryptoSuite) {
    fbb_.AddElement<uint8_t>(SrtpParameters::VT_CRYPTOSUITE, static_cast<uint8_t>(cryptoSuite), 0);
  }
  void add_keyBase64(::flatbuffers::Offset<::flatbuffers::String> keyBase64) {
    fbb_.AddOffset(SrtpParameters::VT_KEYBASE64, keyBase64);
  }
  explicit SrtpParametersBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SrtpParameters> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SrtpParameters>(end);
    fbb_.Required(o, SrtpParameters::VT_KEYBASE64);
    return o;
  }
};

inline ::flatbuffers::Offset<SrtpParameters> CreateSrtpParameters(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    FBS::SrtpParameters::SrtpCryptoSuite cryptoSuite = FBS::SrtpParameters::SrtpCryptoSuite::AEAD_AES_256_GCM,
    ::flatbuffers::Offset<::flatbuffers::String> keyBase64 = 0) {
  SrtpParametersBuilder builder_(_fbb);
  builder_.add_keyBase64(keyBase64);
  builder_.add_cryptoSuite(cryptoSuite);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SrtpParameters> CreateSrtpParametersDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    FBS::SrtpParameters::SrtpCryptoSuite cryptoSuite = FBS::SrtpParameters::SrtpCryptoSuite::AEAD_AES_256_GCM,
    const char *keyBase64 = nullptr) {
  auto keyBase64__ = keyBase64 ? _fbb.CreateString(keyBase64) : 0;
  return FBS::SrtpParameters::CreateSrtpParameters(
      _fbb,
      cryptoSuite,
      keyBase64__);
}

inline const ::flatbuffers::TypeTable *SrtpCryptoSuiteTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::SrtpParameters::SrtpCryptoSuiteTypeTable
  };
  static const char * const names[] = {
    "AEAD_AES_256_GCM",
    "AEAD_AES_128_GCM",
    "AES_CM_128_HMAC_SHA1_80",
    "AES_CM_128_HMAC_SHA1_32"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_ENUM, 4, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *SrtpParametersTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_STRING, 0, -1 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::SrtpParameters::SrtpCryptoSuiteTypeTable
  };
  static const char * const names[] = {
    "cryptoSuite",
    "keyBase64"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

}  // namespace SrtpParameters
}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_SRTPPARAMETERS_FBS_SRTPPARAMETERS_H_
