// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: singal.proto

#include "singal.pb.h"
#include "singal.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace server {

static const char* WebRtcService_method_names[] = {
  "/server.WebRtcService/Sync",
};

std::unique_ptr< WebRtcService::Stub> WebRtcService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< WebRtcService::Stub> stub(new WebRtcService::Stub(channel, options));
  return stub;
}

WebRtcService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Sync_(WebRtcService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::server::WorkerToServer, ::server::ServerToWorker>* WebRtcService::Stub::SyncRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::server::WorkerToServer, ::server::ServerToWorker>::Create(channel_.get(), rpcmethod_Sync_, context);
}

void WebRtcService::Stub::async::Sync(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::server::WorkerToServer,::server::ServerToWorker>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::server::WorkerToServer,::server::ServerToWorker>::Create(stub_->channel_.get(), stub_->rpcmethod_Sync_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::server::WorkerToServer, ::server::ServerToWorker>* WebRtcService::Stub::AsyncSyncRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::server::WorkerToServer, ::server::ServerToWorker>::Create(channel_.get(), cq, rpcmethod_Sync_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::server::WorkerToServer, ::server::ServerToWorker>* WebRtcService::Stub::PrepareAsyncSyncRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::server::WorkerToServer, ::server::ServerToWorker>::Create(channel_.get(), cq, rpcmethod_Sync_, context, false, nullptr);
}

WebRtcService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WebRtcService_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< WebRtcService::Service, ::server::WorkerToServer, ::server::ServerToWorker>(
          [](WebRtcService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::server::ServerToWorker,
             ::server::WorkerToServer>* stream) {
               return service->Sync(ctx, stream);
             }, this)));
}

WebRtcService::Service::~Service() {
}

::grpc::Status WebRtcService::Service::Sync(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::server::ServerToWorker, ::server::WorkerToServer>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace server

